### ISSUE TITLE
No Module Found

### ISSUE THREAD

**Issue by Chutlhu** [childsish/dynamic-yaml#1]
Hi!
I ve installed package as you explain in the readme.
However I am getting the following error:

```bash
    from yaml_wrappers import YamlDict, YamlList
ModuleNotFoundError: No module named 'yaml_wrappers'
```
I am using python3.6.8

**Comment by childsish** [comment]
Thanks for pointing this out. I've made two changes:
1. I've updated the code to be compatible with only Python 3 (the root cause). Python 2 is no longer supported.
2. I've added the package to PyPI. Now installation should be as simple as `pip install dynamic-yaml`

**Comment by Chutlhu** [comment]
Thank you very much, friend of the ancient ones
