### ISSUE TITLE
variable substitution doesn't work under "|" multi-line 

### ISSUE THREAD

**Issue by victorchwai** [childsish/dynamic-yaml#21]
Hi, 

would it be possible to support variable substitution under the multi-line "|" in dynamic-yaml:

For exampe:

yaml_info = '''
topo:
  link1:
    link:
      Dut1: port10
      Dut2: port10
    type: rvi
    lag: None
    ip: 101.1.1.0/24

configs:
  Dut1:
    config: |
            config switch interface
              edit {topo.link1.link.Dut1}          # <<< fails here
                set allowed-vlan 10
              next
            end
    config2: "edit {topo.link1.link.Dut1}"   # <<< works here
'''

y = dynamic_yaml.load(yaml_info)
dy= yaml.safe_load(dynamic_yaml.dump(y))

pprint.pprint(dy)
{'configs': {'Dut1': {'config': 'config switch interface\n'
                                '  edit {topo.link1.link.Dut1}\n'
                                '    set allowed-vlan 10\n'
                                '  next\n'
                                'end\n',
                      'config2': 'edit port10'}},
 'topo': {'link1': {'ip': '101.1.1.0/24',
                    'lag': 'None',
                    'link': {'Dut1': 'port10', 'Dut2': 'port10'},
                    'type': 'rvi'}}}

Thanks in advance,

- Victor

**Comment by childsish** [comment]
Hi Victor, could you give try branch `implement_multiline_support` (#23) to see if it solves your problem?

Cheers,
Liam

**Comment by victorchwai** [comment]
Hi Liam,

thanks a lot for prompt help. It's working fine now.

- Victor
