### ISSUE TITLE
'YamlDict' has no __delattr__ method

### ISSUE THREAD

**Issue by Mystikite** [childsish/dynamic-yaml#25]
Is there a reason __delattr__ isn't implemented on YamlDict?
It was a bit surprising to try to delete an attribute and have it raise.

**Comment by childsish** [comment]
I suppose it's because of two reasons. 1) I always used `del obj['key']`. 2) It's meant to be for settings and parameters which typically don't get deleted.

Nevertheless, it's an easy functionality to implement.
