### ISSUE TITLE
No dynamic changes

### ISSUE THREAD

**Issue by Chutlhu** [childsish/dynamic-yaml#3]
Dear Childsish,
I was able to install the package and load it in python, but I not noticing the 'dynamic substitutions' of the entries:
Using your toyexample, here is the output:

```python
In [14]: with open(cfg_file) as fileobj: 
    ...:     cfg = dynamic_yaml.load(fileobj) 
    ...:     print(cfg) 
    ...:                                                                
{'project_name': 'hello-world', 'dirs': {'home': '/home/user', 'venv': '{dirs.home}/venvs/{project_name}', 'bin': '{dirs.venv}/bin', 'data': '{dirs.venv}/data', 'errors': '{dirs.data}/errors', 'sessions': '{dirs.data}/sessions', 'databases': '{dirs.data}/databases'}, 'exes': {'main': '{dirs.bin}/main', 'test': 'tests'}}


```

**Comment by childsish** [comment]
The substitutions are evaluated when accessing the variable. You should see the substitution occur when you execute `print(cfg.dirs.venv)`. I could also update the `__str__` function to also evaluate the variables dynamically, but I'm currently unable to think of a good use case.

**Comment by childsish** [comment]
This does not seem to be an issue.
