### ISSUE TITLE
Longer dependencies

### ISSUE THREAD

**Issue by MTDzi** [childsish/dynamic-yaml#4]
Hi,
I'd like to be able to define a relationship like this:
```
prefix: /opt/ml

input_path: "{prefix}/input"

training_data_path: '{input_path}/data/training'
```

I.e. it would be awesome if dynamic-yaml would parse `training_data_path` as `'/opt/ml/input/data/training'`.

Currently, I'm getting:
```
'training_data_path': '{prefix}/input/data/training/'
```

**Comment by childsish** [comment]
Thanks for the suggestion :) I've created a new version (1.2.0) that now resolves dependencies recursively. I've made it opt-in to preserve backwards compatibility. Just run:
```
load(config, recursive=True)
```
to set the YAML object to resolve its dependencies recursively.

**Comment by MTDzi** [comment]
Just checked and it works like a charm.

👍
